### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by durcheinandr** [Sakrecoer/DT-webgallery#1]
It would be nice to add instructions how to install

**Comment by Sakrecoer** [comment]
You can't install it. It is just a mockup/sketch that was meant to be adapted by the draktable dev if they liked it. They didn't, at least not in this form (how the images scale). You could easily adapt it to a jekyll template though, or you could use these:
https://github.com/Jack000/Expose
https://github.com/Rouslan/PyExpose
